### PR TITLE
Dtb events num of events

### PR DESCRIPTION
**Pull request by Mtneer**
# Description
Added a "number of events" indicator next to each month sub-heading in the events List. Adjusted the layout and styling slightly
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
Check that the number next to the month sub-headings updates with the number of events in that month
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by MandyC6420** [comment]
Love the scrollies!!!  Thanks!

**Review by MandyC6420 — APPROVED** [review]
Great Job David!!

**Comment by pattiperry** [comment]
looks great david! glad you got it figured out!

**Comment by mattspence338** [comment]
Looks good and everything works for me

**Pull request merged**
